### PR TITLE
Created tables in sqlite

### PR DESCRIPTION
**Pull request by gargnishith**
This time i made all the changes in app.py but i have to create a new file as connection.py only to create a table in database if i add that code of connection in app.py then whenever that app.py code willl run on one system then at that time there is creation of that table again and again and that can table can be created only once so everytime first you have to run connection.py then go for app.py. I also added a new file in templates and static also named as aftersignup.html and aftersignup.css.

### CODE REVIEW

**Comment by TheLethalCode** [comment]
This is better. I was actually asking you to check if the database exists, and if it doesn't to create it. But never mind, this works too. Ho and btw, when you login, that is not how you check for the user. Do not go through all the data of the database manually. Use the "WHERE" command. That is a better way. @dewangmodi was also working on this. I will take the better features of both your PR and merge it.

**Comment by gargnishith** [comment]
@TheLethalCode is it necessary to change that syntax to WHERE clause? So that i have to send a new PR including that WHERE clause.

**Comment by TheLethalCode** [comment]
You don't have to send a separate PR. Just push your commit, and it will be updated in the current PR itself. And yeah, using WHERE optimises the code

**Comment by gargnishith** [comment]
I have applied that where clause in sqlite.

**Pull request merged**
