### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by adamdavis99**

### CODE REVIEW

**Comment by TheLethalCode** [comment]
Hey, I would like all the front end related stuff to be under the "static" folder. So move the fonts, css folder under the static folder. And what are the sass cache files?

**Comment by adamdavis99** [comment]
So I'll then put all the html css pages under static folder and create
another pull request?
And regarding the sass cache, I'll delete them, since I downloaded the
images from net, so these things might have been downloaded additionally.

**Comment by TheLethalCode** [comment]
You dont have to send another PR! Just commit your changes, it will automatically update. And yeah, put all HTML files under templates folder. And move them all under static

**Comment by adamdavis99** [comment]
I'll surely do it, thanks for correcting me regarding pr's of github
Extremely newbie

**Comment by TheLethalCode** [comment]
Yeah sure, no worries. Everyone learns with experience

**Comment by TheLethalCode** [comment]
Hey, the website looks really good. There are still some more changes. Here are all the changes I would like:-
1) Don't change the repo structure. So, have the index.html, signin.html in the templates folder. And all your scripts under the js folder, which should be placed under the static folder. The same goes for your css folder. Place it under the static folder. I guess this will change your internal hyperlinks too. So take care of it.
2) Delete the unnecessary cache files. And if you aren't using all those fonts, delete them. Make your working directory clean.
These are the main changes. So, take care of it. Push the changes after commiting. That should be enough for merging.

**Comment by adamdavis99** [comment]
I have changed the file locations as per you said. Regarding the sass-cache, since I have downloaded the css fonts from internet, these files have also been automatically downloaded. So I have kept them for proper working of the css files. When I searched the internet, it says sass cache files are some cache files which speeds up compilation process.
https://stackoverflow.com/questions/37618066/generate-css-from-scssc-file-in-sass-cache
So I am keeping these files. You can check them. Still if you feel that these files are useless, I will surely delete them.

**Comment by adamdavis99** [comment]
Since I don't have much idea about the working of these files, I am not deleting them.

**Comment by TheLethalCode** [comment]
Hey, it seems all the internal form elements are being changed and the internal hyperlinks are misplaced. So the backend is being affected and lot of 404 error keeps popping up. I am closing the PR for now. Make a new PR when you are done

**Comment by adamdavis99** [comment]
New PR#44 have a look

**Pull request closed without merging**
