### PR TITLE
Newer and better webpages

### PR DESCRIPTION
**Pull request by adamdavis99**
I have changed the design of webpages to make them look even more cool. Please do have a look, although I will try to do even more modifications.

### CODE REVIEW

**Comment by TheLethalCode** [comment]
@adamdavis99  when you send a PR adding new functionalities, check whether the previous functionalities are working. Your PR, is almost incompatible with the backend. Take care not to change the form attribute's names and all other internal hyperlinks. And also maintain the repo hierarchy.

**Comment by adamdavis99** [comment]
I have tried to keep the class and id attributes same. With some minor additions, I will be making more changes.

**Comment by adamdavis99** [comment]
Created the music webpage to some extent.  Will add some more functionalities by tomorrow

**Comment by TheLethalCode** [comment]
Looks good. I am merging this now, but I would like some changes done.
1) In the index.html, it seems the box is going out of the screen, and I can't scroll down to see it end either. See if you can take care of that
2) In profile.html, change the background, the contents aren't visible. Also comment out the watch later division for now. Also, make the search bar smaller and shift the logout option to the opposite side. And it would be better if you made the buttons bigger.
For now, these are the priority.
As I have said before, your PR's are giving unnecessary merge conflicts. I think you aren't syncing your local repo with this one. In a local repo, you are supposed to have to remote urls. One for your forked repository(origin) and the other to the main one(upstream)( in this case, mine). You have to regularly pull from upstream to keep it synced. Google this if you don't understand. Try to first update your local repo with the remote urls, then go for the changes. This might help you:- https://github.com/ritjoe/hfoss/wiki/upstream-vs-origin

**Comment by adamdavis99** [comment]
https://github.com/ritjoe/hfoss/wiki/upstream-vs-origin Since I am using Github Desktop and not git commands so I am facing a little problem in all these things. I will keep a track of pulling from upstream to keep a track of the newly made changes. For the index page, my laptop is showing everything properly and no box is going out of screen. So can you please send me a screenshot of how the index page is showing on your computer so that I can identify the problems?

**Comment by TheLethalCode** [comment]
Leave the index page then, I guess its only in mine. It would be better if you can use git command line, but if you can manage otherwise it is well and good

**Pull request merged**
