### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by adamdavis99**
I have created a few changes to the main webpage. Please have a look. I hope this time it won't conflict with all the backend processes.

### CODE REVIEW

**Comment by adamdavis99** [comment]
I can't understand why Github is unable to merge automatically from my devel branch to your devel branch??
It is able to merge automatically when I change your branch to master branch.

**Comment by adamdavis99** [comment]
Added Facebook and Google signup option buttons.

**Comment by TheLethalCode** [comment]
Don't worry about the merge. It means you were not working with the latest copy of the repo. I will handle it. But since this changes a lot of frontend, and I have to test the backend with your frontend, it will take some time for me to test and merge it. Sorry, in advance

**Comment by adamdavis99** [comment]
I have made some changes to the profile webpage. Just pictures and colors are changed to make it look better. Please do have a look.

**Comment by TheLethalCode** [comment]
Sorry it took some time, I was out of station for a while. Nice additions, though we might need to change the background. Will merge it soon.

**Comment by TheLethalCode** [comment]
@adamdavis99 I have merged it. There are 2 changes I would like. 
1) Change the background.
2) Remove the unnecessary fonts

**Pull request merged**
